version: "3"

services:
  build:
    build: "."
    volumes:
      - .:/gluon
      - /gluon/node_modules
    command: npm run build
    environment:
      - GLUON_IN_DOCKER="yes"
    links:
      - mysql

  test:
    build: "."
    environment:
      - NODE_ENV=test
      - GLUON_IN_DOCKER="yes"
    volumes:
      - .:/gluon
      - /gluon/node_modules
    command: npm run test
    links:
      - mysql

  mysql:
    image: "mysql:5.5"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=gluon
      - MYSQL_PASSWORD=gluon
      - MYSQL_DATABASE=gluon
